### ISSUE TITLE
[Git-It Guide] Challenge #10 - Requesting You Pull Please

### ISSUE THREAD

**Issue by KyleFlemington** [jlord/patchwork#13970]
Hi There,
I feel like I made a mistake earlier in this module and it's causing issues now. 

---

**vagrant [patchwork (gh-pages)⚡]> git-it verify**
Verifying "REQUESTING YOU PULL, PLEASE"...

ACTUAL  
""  
EXPECTED
!= "Found your pull request!"     

FAIL
Your solution to REQUESTING YOU PULL, PLEASE didn't match the expected output.

Try again

---

**Username/patchwork/branches**

<img width="1017" alt="screen shot 2016-09-01 at 4 09 02 pm" src="https://cloud.githubusercontent.com/assets/20758659/18187461/917ddff0-705e-11e6-8cbc-928796b83918.png">

---

**Terminal**

<img width="574" alt="screen shot 2016-09-01 at 4 14 41 pm" src="https://cloud.githubusercontent.com/assets/20758659/18187538/4347ace8-705f-11e6-8076-568676cf8593.png">

---

Thank you for any advice and feedback,
Kyle

**Comment by jlord** [comment]
Hi!

You made a pull request https://github.com/jlord/patchwork/pull/13965 earlier, but the file you added wasn't in the right spot, which is why it wasn't merged. 

I'm doing some cleaning/bug fixing in Git-it/@reporobot right now and just did a batch close of un-merged PRs, but you can still try again with the file in the `contributors` folder.
