### ISSUE TITLE
Repo takes a long time to load

### ISSUE THREAD

**Issue by stevemoser** [jlord/patchwork#15111]
Expected:
I can quickly download a repo that is only used for learning purposes.

Actual:
I have to wait a long time to download the whole history of this repo which isn't important to this exercise.

I imagine either the repo needs to be modified or created new every so often to erase the large commit history or instruct users how to do a [shallow clone](http://blogs.atlassian.com/2014/05/handle-big-repositories-git/). Both have their pros and cons.

/cc @jlord.

**Comment by jlord** [comment]
Yeah, definitely want to make this a smaller repo 💯 

I have a similar issue opened up: https://github.com/jlord/reporobot/issues/29, the server that works with this repo. I'll close this here as a dupe and point people to ☝️ to track the issue since that's where the development to solve this will eventually land. Hopefully it's not too long before I can get that taken care of ✨
