### ISSUE TITLE
error: invalid path 'CONTRIBUTORS/add-willwalsh96.txt.

### ISSUE THREAD

**Issue by zimmerry** [jlord/patchwork#40383]
@jlord The file from @willwalsh96 has a trailing "." in the filename, which is an invalid filename in windows and causes this error:

`Cloning into 'patchwork'...
remote: Enumerating objects: 412368, done.
remote: Counting objects: 100% (242/242), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 412368 (delta 119), reused 228 (delta 108), pack-reused 412126
Receiving objects: 100% (412368/412368), 154.54 MiB | 10.43 MiB/s, done.
Resolving deltas: 100% (197878/197878), done.
error: invalid path 'CONTRIBUTORS/add-willwalsh96.txt.'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'`

**Comment by t-weij** [comment]
I've got the same issue, making it unable to proceed

**Comment by javorac** [comment]
I had the same problem and this command worked for me : 
  checkout -b add-YOURUSERNAME

**Comment by javorac** [comment]
I've meant:
   git checkout -b add-YOURUSERNAME

**Comment by Josehower** [comment]
After checking the problem. was found that the bot that merge only check for the first part of the name in order to apply the merge.

The way was fixed was doing a revert pull request 

Because the bot checked for the username I create a new github acount named willwalsh9

https://github.com/jlord/patchwork/pull/40480

And did a revert request deleting the file `CONTRIBUTORS/add-willwalsh96.txt.`

This is a nice story but at the same time a vulnerability of the system.

@karlhorky create a PR to fix this issue on the bot here https://github.com/jlord/reporobot/pull/41/files

have a nice day!
